/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 9
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 1
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ident = 1,
  aux_sym_WHITESPACE_token1 = 2,
  sym_DOC_LINE = 3,
  sym_DOC_BLOCK = 4,
  sym_LINE_COMMENT = 5,
  sym_MULTI_LINE_COMMENT = 6,
  sym_WHITESPACE = 7,
  sym_COMMENT = 8,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [aux_sym_WHITESPACE_token1] = "WHITESPACE_token1",
  [sym_DOC_LINE] = "DOC_LINE",
  [sym_DOC_BLOCK] = "DOC_BLOCK",
  [sym_LINE_COMMENT] = "LINE_COMMENT",
  [sym_MULTI_LINE_COMMENT] = "MULTI_LINE_COMMENT",
  [sym_WHITESPACE] = "WHITESPACE",
  [sym_COMMENT] = "COMMENT",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [aux_sym_WHITESPACE_token1] = aux_sym_WHITESPACE_token1,
  [sym_DOC_LINE] = sym_DOC_LINE,
  [sym_DOC_BLOCK] = sym_DOC_BLOCK,
  [sym_LINE_COMMENT] = sym_LINE_COMMENT,
  [sym_MULTI_LINE_COMMENT] = sym_MULTI_LINE_COMMENT,
  [sym_WHITESPACE] = sym_WHITESPACE,
  [sym_COMMENT] = sym_COMMENT,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_WHITESPACE_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_DOC_LINE] = {
    .visible = true,
    .named = true,
  },
  [sym_DOC_BLOCK] = {
    .visible = true,
    .named = true,
  },
  [sym_LINE_COMMENT] = {
    .visible = true,
    .named = true,
  },
  [sym_MULTI_LINE_COMMENT] = {
    .visible = true,
    .named = true,
  },
  [sym_WHITESPACE] = {
    .visible = true,
    .named = true,
  },
  [sym_COMMENT] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '+') ADVANCE(4);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '+') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '+') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(10);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_WHITESPACE_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_DOC_LINE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_DOC_BLOCK);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_LINE_COMMENT);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_LINE_COMMENT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_MULTI_LINE_COMMENT);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_MULTI_LINE_COMMENT);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {(TSStateId)(-1),},
  [4] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_WHITESPACE] = STATE(0),
    [sym_COMMENT] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [aux_sym_WHITESPACE_token1] = ACTIONS(3),
    [sym_DOC_LINE] = ACTIONS(5),
    [sym_DOC_BLOCK] = ACTIONS(5),
    [sym_LINE_COMMENT] = ACTIONS(7),
    [sym_MULTI_LINE_COMMENT] = ACTIONS(7),
  },
  [STATE(1)] = {
    [sym_WHITESPACE] = STATE(1),
    [sym_COMMENT] = STATE(1),
    [aux_sym_WHITESPACE_token1] = ACTIONS(9),
    [sym_DOC_LINE] = ACTIONS(5),
    [sym_DOC_BLOCK] = ACTIONS(5),
    [sym_LINE_COMMENT] = ACTIONS(7),
    [sym_MULTI_LINE_COMMENT] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_WHITESPACE] = STATE(2),
    [sym_COMMENT] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(11),
    [aux_sym_WHITESPACE_token1] = ACTIONS(3),
    [sym_DOC_LINE] = ACTIONS(5),
    [sym_DOC_BLOCK] = ACTIONS(5),
    [sym_LINE_COMMENT] = ACTIONS(7),
    [sym_MULTI_LINE_COMMENT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
  [4] = 1,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 4,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_WHITESPACE, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_COMMENT, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_somnium(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
    .name = "somnium",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
